test:
  dataset_type: "single"
  process_type: "test"
  data_dir: "./"
  json_dir: "./json_file"
  mel_dir: "./mel_file"
  batch_size: 64
  shuffle: false
  dataset_file: "mead"

# model:
#   drop_path_rate: 0.0
#   head_init_scale: 1.0
#   in_chans: 1
#   num_classes: 8

backbone:
  in_chans: 1
  num_classes: 8
  drop_path_rate: 0.
  head_init_scale: 1.
  height: 128
  width: 160
  is_pos_encoding: true
  is_backbone: false

# attention:
#   dim: 768
#   num_classes: 4
#   num_heads: 4
#   qkv_bias: false
#   qk_scale: null
#   attn_drop: 0.
#   proj_drop: 0.

device: "cuda"
save_dir: "output/convnext/logs_10/eval"
model_type: convnext
model_size: "tiny"
checkpoint_path: "output/convnext/logs_10/ckpt/best_model.pth"