train:
  dataset_type: "single"
  process_type: "train"
  data_dir: "./"
  json_dir: "./json_file"
  mel_dir: "./mel_file"
  batch_size: 64
  shuffle: true
  dataset_file: "iemocap"

valid:
  dataset_type: "single"
  process_type: "valid"
  data_dir: "./"
  json_dir: "./json_file"
  mel_dir: "./mel_file"
  batch_size: 64
  shuffle: false
  dataset_file: "iemocap"

model:
  num_classes: 4
  dropout_rate: 0.5
  linear_layer_size: 640
  filter_sizes: [64, 48, 32, 32]

mel:
  dataset_file: "iemocap"
  data_dir: "./data"
  save_dir: "./mel_file"
  sr: 16000
  hop_length: 512

device: "cuda"
log_dir: "output/laughter_detection"
is_continue: false
model_type: resnet
model_size: "small"  # tiny, small, base, large, xlarge
checkpoint_path: "output/convnext/logs_6/ckpt/best_model.pth"
num_epochs: 100
initial_lr: 0.001