train:
  process_type: "train"
  dataset_type: "single"
  data_dir: "./"
  json_dir: "./json_file"
  mel_dir: "./mel_file"
  batch_size: 64
  shuffle: true
  dataset_file: "mead"

valid:
  process_type: "valid"
  dataset_type: "single"
  data_dir: "./"
  json_dir: "./json_file"
  mel_dir: "./mel_file"
  batch_size: 64
  shuffle: false
  dataset_file: "mead"

model:
  num_classes: 4
  dropout_rate: 0.5
  linear_layer_size: 640
  filter_sizes: [64, 48, 32, 32]

mel:
  dataset_file: "mead"
  data_dir: "./data"
  save_dir: "./mel_file"
  sr: 16000
  hop_length: 512

device: "cuda"
log_dir: "output/laughter_detection"
model_type: "resnet"
is_continue: false
checkpoint_path: "output/laughter_detection/logs_1/ckpt/best_model.pth"
start_epoch: 101
num_epochs: 200